### PR TITLE
user: test-wifi: split into rlite-wifi; clean up interface

### PR DESCRIPTION
**Pull request by autrimpo**
I've split the code into the *rlite-wifi* library.

I decided to remove the unused functions and only leave the ones we agreed *shim-wifi* will use, plus added init/close functions for handling the control interface. This was done mostly because a lot of the code is just handling the network list, which we in the end don't use and the naming was getting quite confusing - `wifi_cmd_add_net` would call the new interface function `wifi_?_net_add` which would call `wifi_add_network_to_config` which would call `wifi_add_network`. If the *shim-wifi* does not need it, I see no point in having the code in, as the `wpa_cli` utility is quite user friendly and can be use to accomplish all the things one would need. `test-wifi` is thus used to only test the library, with any additional work being left to `wpa_cli`.

I've tried to document the library in the header, but most of the functions are pretty self-explanatory.

### CODE REVIEW

**Comment by vmaffione** [comment]
Thanks, it looks great! Indeed, we don't need to replicate wpa_cli.
But we actually for the shim-wifi need "wifi_scan" to get the list of current SSIDs with at least the signal strength. The idea is that a RINA node physically moves, and as it moves it can automatically connect to different SSID, deciding when to switch depending on the signal strength. In other words, we would like the uipcps daemon to automatically handle the handover as it happens within the cellular network.

**Comment by autrimpo** [comment]
I've pushed an amended commit that includes `wifi_scan()` as well (+ stuff to test it in test-wifi).
I did a small change, that is that it deallocates the list before scannig, so the user can just reuse the same struct to get updated information.

**Comment by vmaffione** [comment]
Looks great, thanks

**Comment by vmaffione** [comment]
FYI I moved test-wifi to user/tools, where it makes more sense.

**Comment by autrimpo** [comment]
I see, thanks for the info.

**Pull request merged**
